# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Job1
    steps:
    - script: echo Hello, world from Job1! using ${variable}
      displayName: 'Job1'

  - job: Job2
    dependsOn: Job1
    steps:
    - script: echo Hello, world from Job2!
      displayName: 'Job2'

  - job: Job3
    dependsOn: Job1
    steps:
    - script: echo Hello, world from Job3!
      displayName: 'Job3'

  - job: Job4
    dependsOn: 
    - Job2
    - Job3
    steps:
    - script: echo Hello, world from Job4!
      displayName: 'Job4'