# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Hello, world from Job1!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo this is added to show multi line script running
    displayName: 'Run a multi-line script'
- job: Job2
  steps:
  - script: echo Hello, world from Job2!
    displayName: 'Run a one-line script'